package jp.archilogic.docnext.android.type;

public enum TaskErrorType {
    NETWORK_UNAVAILABLE , NETWORK_ERROR , STORAGE_NOT_MOUNTED , NO_STORAGE_SPACE , STATUS_CODE_401 , STATUS_CODE_403 ,
    STATUS_CODE_403_USERID , STATUS_CODE_403_UA , STATUS_CODE_404 , STATUS_CODE_408 , STATUS_CODE_500;
}
